name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  id-token: write
  attestations: write
  contents: write

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Prepare release
#         run: .github/workflows/prepare_release.py --tag ${GITHUB_REF_NAME}
#       - name: Draft release
#         uses: softprops/action-gh-release@v2
#         with:
#           draft: false
#           prerelease: true
#           generate_release_notes: true
#           body_path: release_notes.txt
#           fail_on_unmatched_files: true
#           files: depend_on_what_you_use-*.tar.gz

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.2.2
    with:
      prerelease: true
      release_files: depend_on_what_you_use-*.tar.gz
      #tag_name: ${{ inputs.tag_name || github.ref_name }}
      tag_name: ${{ inputs.tag_name }}
      mount_bazel_caches: false
      bazel_test_command: "/bin/true"
